import java.util.Scanner;

class Program {

    private static double safeScheme(int years) {
        return years < 3 ? 6 : 7;
    }

    public static void main(String[] args) {
        var input = new Scanner(System.in);
        System.out.print("Amount and Period: ");
        double p = input.nextDouble();
        int n = input.nextInt();
        Investment inv = new Investment(p, n);
        System.out.printf("Future value in riskless investment: %.2f%n", inv.futureValue(Program::safeScheme));
        double bi = 8.75;
        //passing lambda expression (reference to an anonymous method generated by the
        //compiler from the body of the expression), local variable(bi) of enclosing 
        //method(main) is captured by copy making it effectively final
        System.out.printf("Future value in riskful investment : %.2f%n", inv.futureValue(y -> bi + 0.25 * y));
        input.close();
    }
}
